// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
      case TargetPlatform.linux:
      case TargetPlatform.fuchsia:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAPMSZ2FJfOVrddW5d3GBl8c-oYWyQcg30',
    appId: '1:835942942857:web:db639e04e85231cba89e58',
    messagingSenderId: '835942942857',
    projectId: 'synclife-e3763',
    authDomain: 'synclife-e3763.firebaseapp.com',
    storageBucket: 'synclife-e3763.firebasestorage.app',
    measurementId: 'G-BXPWPYR1ZD',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBI3_7kYm6vhs1u5ZyGfUjF4bZFGNEx58Q',
    appId: '1:835942942857:android:8da763664fd47c69a89e58',
    messagingSenderId: '835942942857',
    projectId: 'synclife-e3763',
    storageBucket: 'synclife-e3763.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC1aj4uxrpy6CjX-rfFqBb0yCgjxcpLnQE',
    appId: '1:835942942857:ios:3cf77bdd811b365ea89e58',
    messagingSenderId: '835942942857',
    projectId: 'synclife-e3763',
    storageBucket: 'synclife-e3763.firebasestorage.app',
    iosBundleId: 'com.synclife.app',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyC1aj4uxrpy6CjX-rfFqBb0yCgjxcpLnQE',
    appId: '1:835942942857:ios:3cf77bdd811b365ea89e58',
    messagingSenderId: '835942942857',
    projectId: 'synclife-e3763',
    storageBucket: 'synclife-e3763.firebasestorage.app',
    iosBundleId: 'com.synclife.app',
  );
}